### ISSUE TITLE
Adding back Score Card in mobile and tablet sizes 

### ISSUE THREAD

**Issue by HJain13** [HJain13/Tic-Tac-Toe#1]
I have a scorecard in Desktop view (>=1000px) but hid it in lesser screen sizes because I couldn't decide how to place them. Its been some time since I worked on this and since its a simple task, I wanted to give a chance to first-timers/beginners.

**Comment by faahim** [comment]
Hey there! I'd like try this one out! Can I take it? 😺

**Comment by faahim** [comment]
Okay, I tinkered with it a little bit and this is what I came up with: https://imgur.com/MuFlqSd

I was first trying with the big score number style. But it wasn't looking very good to me. Also, it was taking too much space for a small screen. So I tried to make it compact.

Let me know what you think! 😃

**Comment by HJain13** [comment]
@faahim This looks good, Push your commit and PR, I will include it. :) 👍

**Comment by faahim** [comment]
Great! 😄 I'll be sending a pull request soon!

**Comment by faahim** [comment]
Done! I've sent the PR. Please review. :)
